[buteo-sync-plugin-webcal] Use lcWebCal logging category instead of Buteo LOG_* macros. JB#53712
sailfishos/buteo-sync-plugin-webcal pull request #2
Opened 2021-08-11 06:13 UTC by blammit

2021-08-11 07:32 UTC, dcaliste requested changes
Like in the CalDAV plugin, I put also a line like `qputenv("MSYNCD_LOGGING_LEVEL", "8");` in the tests. It needs to be updated.

Thank you for the changes here to use Qt logging categories.

2021-08-13 10:53 UTC, pvuorela commented on src/webcalclient.h
> +Q_DECLARE_LOGGING_CATEGORY(lcWebCal)
Since only one .cpp uses logging, suppose this is not absolutely needed.

2021-08-13 10:54 UTC, pvuorela approved these changes
Seems simple and good, and suppose could be merged already

2021-08-13 10:55 UTC, pvuorela commented
Oh, didn't notice Damien's comment on the code tab. Removal enough maybe?

2021-08-13 12:26 UTC, dcaliste commented
> Removal enough maybe?

Yes, indeed, one can completely remove the line making the `qsetenv`. After all, I put it there the first time in CalDAV to actually don't have to remember it... While, now that we're using standard Qt logging, one can turn on or off the debug messages with a standard way.

2021-08-18 01:15 UTC, chriadam approved these changes

2021-08-29 00:22 UTC, merged